import { WORLD_COUNTRY_BORDER_OVERLAY } from './mapBoundaryOverlays.js?v=20260822-map-borders-1';

export const TROPICAL_WORLD_BORDER_OVERLAY = WORLD_COUNTRY_BORDER_OVERLAY;

export const TROPICAL_REFERENCE_OVERLAYS = Object.freeze([
  TROPICAL_WORLD_BORDER_OVERLAY,
]);
