// warningColors.js
// Export color mapping
export const warningColors = {
    "Tsunami Warning": "#FD6347",
    "Tornado Warning": "#FF0000",
    "Extreme Wind Warning": "#FF8C00",
    "Severe Thunderstorm Warning": "#FFA500",
    "Flash Flood Warning": "#8B0000",
    "Flash Flood Statement": "#8B0000",
    "Severe Weather Statement": "#00FFFF",
    "Shelter In Place Warning": "#FA8072",
    "Evacuation Immediate": "#7FFF00",
    "Civil Danger Warning": "#FFB6C1",
    "Nuclear Power Plant Warning": "#4B0082",
    "Radiological Hazard Warning": "#4B0082",
    "Hazardous Materials Warning": "#4B0082",
    "Fire Warning": "#A0522D",
    "Civil Emergency Message": "#FFB6C1",
    "Law Enforcement Warning": "#C0C0C0",
    "Storm Surge Warning": "#B524F7",
    "Hurricane Force Wind Warning": "#CD5C5C",
    "Hurricane Warning": "#DC143C",
    "Typhoon Warning": "#DC143C",
    "Special Marine Warning": "#FFA500",
    "Blizzard Warning": "#FF4500",
    "Snow Squall Warning": "#C71585",
    "Ice Storm Warning": "#8B008B",
    "Heavy Freezing Spray Warning": "#00BFFF",
    "Winter Storm Warning": "#FF69B4",
    "Lake Effect Snow Warning": "#008B8B",
    "Dust Storm Warning": "#FFE4C4",
    "Blowing Dust Warning": "#FFE4C4",
    "High Wind Warning": "#DAA520",
    "Tropical Storm Warning": "#B22222",
    "Storm Warning": "#9400D3",
    "Tsunami Advisory": "#D2691E",
    "Tsunami Watch": "#FF00FF",
    "Avalanche Warning": "#1E90FF",
    "Earthquake Warning": "#8B4513",
    "Volcano Warning": "#2F4F4F",
    "Ashfall Warning": "#A9A9A9",
    "Flood Warning": "#00FF00",
    "Coastal Flood Warning": "#228B22",
    "Lakeshore Flood Warning": "#228B22",
    "Ashfall Advisory": "#696969",
    "High Surf Warning": "#228B22",
    "Extreme Heat Warning": "#C71585",
    "Tornado Watch": "#FFFF00",
    "Severe Thunderstorm Watch": "#DB7093",
    "Flash Flood Watch": "#2E8B57",
    "Gale Warning": "#DDA0DD",
    "Flood Statement": "#00FF00",
    "Extreme Cold Warning": "#0000FF",
    "Freeze Warning": "#483D8B",
    "Red Flag Warning": "#FF1493",
    "Storm Surge Watch": "#DB7FF7",
    "Hurricane Watch": "#FF00FF",
    "Hurricane Force Wind Watch": "#9932CC",
    "Typhoon Watch": "#FF00FF",
    "Tropical Storm Watch": "#F08080",
    "Storm Watch": "#FFE4B5",
    "Tropical Cyclone Local Statement": "#FFE4B5",
    "Winter Weather Advisory": "#7B68EE",
    "Avalanche Advisory": "#CD853F",
    "Cold Weather Advisory": "#AFEEEE",
    "Heat Advisory": "#FF7F50",
    "Flood Advisory": "#00FF7F",
    "Coastal Flood Advisory": "#7CFC00",
    "Lakeshore Flood Advisory": "#7CFC00",
    "High Surf Advisory": "#BA55D3",
    "Dense Fog Advisory": "#708090",
    "Dense Smoke Advisory": "#F0E68C",
    "Small Craft Advisory": "#D8BFD8",
    "Brisk Wind Advisory": "#D8BFD8",
    "Hazardous Seas Warning": "#D8BFD8",
    "Dust Advisory": "#BDB76B",
    "Blowing Dust Advisory": "#BDB76B",
    "Lake Wind Advisory": "#D2B48C",
    "Wind Advisory": "#D2B48C",
    "Frost Advisory": "#6495ED",
    "Freezing Fog Advisory": "#008080",
    "Freezing Spray Advisory": "#00BFFF",
    "Low Water Advisory": "#A52A2A",
    "Local Area Emergency": "#C0C0C0",
    "Winter Storm Watch": "#4682B4",
    "Rip Current Statement": "#40E0D0",
    "Beach Hazards Statement": "#40E0D0",
    "Gale Watch": "#FFC0CB",
    "Avalanche Watch": "#F4A460",
    "Hazardous Seas Watch": "#483D8B",
    "Heavy Freezing Spray Watch": "#BC8F8F",
    "Flood Watch": "#2E8B57",
    "Coastal Flood Watch": "#66CDAA",
    "Lakeshore Flood Watch": "#66CDAA",
    "High Wind Watch": "#B8860B",
    "Extreme Heat Watch": "#800000",
    "Extreme Cold Watch": "#5F9EA0",
    "Freeze Watch": "#00FFFF",
    "Fire Weather Watch": "#FFDEAD",
    "Extreme Fire Danger": "#E9967A",
    "911 Telephone Outage": "#C0C0C0",
    "Coastal Flood Statement": "#6B8E23",
    "Lakeshore Flood Statement": "#6B8E23",
    "Special Weather Statement": "#FFE4B5",
    "Marine Weather Statement": "#FFDAB9",
    "Air Quality Alert": "#808080",
    "Air Stagnation Advisory": "#808080",
    "Hazardous Weather Outlook": "#EEE8AA",
    "Hydrologic Outlook": "#90EE90",
    "Short Term Forecast": "#98FB98",
    "Administrative Message": "#C0C0C0",
    "Test": "#F0FFFF",
    "Child Abduction Emergency": "#FFFFFF",
    "Blue Alert": "#FFFFFF"
};

// Export priority mapping
export const warningPriorities = {
    "Tsunami Warning": 1,
    "Tornado Warning": 2,
    "Extreme Wind Warning": 3,
    "Severe Thunderstorm Warning": 4,
    "Flash Flood Warning": 5,
    "Flash Flood Statement": 6,
    "Severe Weather Statement": 7,
    "Shelter In Place Warning": 8,
    "Evacuation Immediate": 9,
    "Civil Danger Warning": 10,
    "Nuclear Power Plant Warning": 11,
    "Radiological Hazard Warning": 12,
    "Hazardous Materials Warning": 13,
    "Fire Warning": 14,
    "Civil Emergency Message": 15,
    "Law Enforcement Warning": 16,
    "Storm Surge Warning": 17,
    "Hurricane Force Wind Warning": 18,
    "Hurricane Warning": 19,
    "Typhoon Warning": 20,
    "Special Marine Warning": 21,
    "Blizzard Warning": 22,
    "Snow Squall Warning": 23,
    "Ice Storm Warning": 24,
    "Heavy Freezing Spray Warning": 25,
    "Winter Storm Warning": 26,
    "Lake Effect Snow Warning": 27,
    "Dust Storm Warning": 28,
    "Blowing Dust Warning": 29,
    "High Wind Warning": 30,
    "Tropical Storm Warning": 31,
    "Storm Warning": 32,
    "Tsunami Advisory": 33,
    "Tsunami Watch": 34,
    "Avalanche Warning": 35,
    "Earthquake Warning": 36,
    "Volcano Warning": 37,
    "Ashfall Warning": 38,
    "Flood Warning": 39,
    "Coastal Flood Warning": 40,
    "Lakeshore Flood Warning": 41,
    "Ashfall Advisory": 42,
    "High Surf Warning": 43,
    "Extreme Heat Warning": 44,
    "Tornado Watch": 45,
    "Severe Thunderstorm Watch": 46,
    "Flash Flood Watch": 47,
    "Gale Warning": 48,
    "Flood Statement": 49,
    "Extreme Cold Warning": 50,
    "Freeze Warning": 51,
    "Red Flag Warning": 52,
    "Storm Surge Watch": 53,
    "Hurricane Watch": 54,
    "Hurricane Force Wind Watch": 55,
    "Typhoon Watch": 56,
    "Tropical Storm Watch": 57,
    "Storm Watch": 58,
    "Tropical Cyclone Local Statement": 59,
    "Winter Weather Advisory": 60,
    "Avalanche Advisory": 61,
    "Cold Weather Advisory": 62,
    "Heat Advisory": 63,
    "Flood Advisory": 64,
    "Coastal Flood Advisory": 65,
    "Lakeshore Flood Advisory": 66,
    "High Surf Advisory": 67,
    "Dense Fog Advisory": 68,
    "Dense Smoke Advisory": 69,
    "Small Craft Advisory": 70,
    "Brisk Wind Advisory": 71,
    "Hazardous Seas Warning": 72,
    "Dust Advisory": 73,
    "Blowing Dust Advisory": 74,
    "Lake Wind Advisory": 75,
    "Wind Advisory": 76,
    "Frost Advisory": 77,
    "Freezing Fog Advisory": 78,
    "Freezing Spray Advisory": 79,
    "Low Water Advisory": 80,
    "Local Area Emergency": 81,
    "Winter Storm Watch": 82,
    "Rip Current Statement": 83,
    "Beach Hazards Statement": 84,
    "Gale Watch": 85,
    "Avalanche Watch": 86,
    "Hazardous Seas Watch": 87,
    "Heavy Freezing Spray Watch": 88,
    "Flood Watch": 89,
    "Coastal Flood Watch": 90,
    "Lakeshore Flood Watch": 91,
    "High Wind Watch": 92,
    "Extreme Heat Watch": 93,
    "Extreme Cold Watch": 94,
    "Freeze Watch": 95,
    "Fire Weather Watch": 96,
    "Extreme Fire Danger": 97,
    "911 Telephone Outage": 98,
    "Coastal Flood Statement": 99,
    "Lakeshore Flood Statement": 100,
    "Special Weather Statement": 101,
    "Marine Weather Statement": 102,
    "Air Quality Alert": 103,
    "Air Stagnation Advisory": 104,
    "Hazardous Weather Outlook": 105,
    "Hydrologic Outlook": 106,
    "Short Term Forecast": 107,
    "Administrative Message": 108,
    "Test": 109,
    "Child Abduction Emergency": 110,
    "Blue Alert": 111
};